language: php

php:
  - 7.1
  - 7.2

install:
 - echo "{\"http-basic\":{\"nova.laravel.com\":{\"username\":\"${NOVA_USERNAME}\",\"password\":\"${NOVA_PASSWORD}\"}}}" > auth.json

before_script:
  - composer install --dev ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - codacycoverage clover build/coverage/xml
