language: php

php:
  - 7.1
  - 7.2

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - echo "{\"http-basic\":{\"nova.laravel.com\":{\"username\":\"${NOVA_USERNAME}\",\"password\":\"${NOVA_PASSWORD}\"}}}" > auth.json

before_script:
  - composer install --no-interaction --prefer-source
  - yarn

script:
  - yarn run check-format
  - yarn run lint
  - php vendor/bin/phpstan analyze
  - php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - codacycoverage clover build/coverage/xml
