language: php

php:
  - 7.1
  - 7.2

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - echo "{\"http-basic\":{\"nova.laravel.com\":{\"username\":\"${NOVA_USERNAME}\",\"password\":\"${NOVA_PASSWORD}\"}}}" > auth.json

before_script:
  - composer install --dev ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - yarn

script:
  - yarn run check-format
  - yarn run lint
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - codacycoverage clover build/coverage/xml
